// /src/data/metraStations.js

const metraStations = {
  "UP-N": [
    { id: "OGILVIE", name: "Ogilvie Transportation Center" },
    { id: "CLYBOURN", name: "Clybourn" },
    { id: "RAVENSWOOD", name: "Ravenswood" },
    { id: "WILMETTE", name: "Wilmette" },
    { id: "WINNETKA", name: "Winnetka" },
    { id: "HIGHLANDPK", name: "Highland Park" },
    { id: "WAUKEGAN", name: "Waukegan" },
    { id: "KENOSHA", name: "Kenosha" },
  ],
  "UP-NW": [
    { id: "OGILVIE", name: "Ogilvie Transportation Center" },
    { id: "ARLHTS", name: "Arlington Heights" },
    { id: "PALATINE", name: "Palatine" },
    { id: "BARRINGTON", name: "Barrington" },
    { id: "CRYSTALLK", name: "Crystal Lake" },
    { id: "WOODSTOCK", name: "Woodstock" },
    { id: "HARVARD", name: "Harvard" },
  ],
  "UP-W": [
    { id: "OGILVIE", name: "Ogilvie Transportation Center" },
    { id: "OAKPARK", name: "Oak Park" },
    { id: "LOMBARD", name: "Lombard" },
    { id: "GLENELLYN", name: "Glen Ellyn" },
    { id: "WHEATON", name: "Wheaton" },
    { id: "GENEVA", name: "Geneva" },
    { id: "ELBURN", name: "Elburn" },
  ],
  "BNSF": [
    { id: "UNION", name: "Union Station" },
    { id: "CICERO", name: "Cicero" },
    { id: "LAVERGNE", name: "LaVergne" },
    { id: "DOWNERSNO", name: "Downers Grove" },
    { id: "NAPERVILLE", name: "Naperville" },
    { id: "AURORA", name: "Aurora" },
  ],
  "MD-N": [
    { id: "UNION", name: "Union Station" },
    { id: "GRAND-CIC", name: "Grand/Cicero" },
    { id: "RIVERGROVE", name: "River Grove" },
    { id: "GLENVIEW", name: "Glenview" },
    { id: "FOXLAKE", name: "Fox Lake" },
  ],
  "MD-W": [
    { id: "UNION", name: "Union Station" },
    { id: "FRANKLIN", name: "Franklin Park" },
    { id: "ROSELLE", name: "Roselle" },
    { id: "ELGIN", name: "Elgin" },
  ],
  "NCS": [
    { id: "UNION", name: "Union Station" },
    { id: "ROSEMONT", name: "Rosemont" },
    { id: "DESPLAINES", name: "Des Plaines" },
    { id: "ANTIOCH", name: "Antioch" },
  ],
  "HC": [
    { id: "UNION", name: "Union Station" },
    { id: "SUMMIT", name: "Summit" },
    { id: "JUSTICE", name: "Justice" },
    { id: "LEMONT", name: "Lemont" },
    { id: "ROMEOVILLE", name: "Romeoville" },
    { id: "LOCKPORT", name: "Lockport" },
    { id: "JOLIET", name: "Joliet" },
  ],
  "RI": [
    { id: "UNION", name: "Union Station" },
    { id: "35TH", name: "35th Street/Lou Jones" },
    { id: "LSS", name: "LaSalle Street Station" },
    { id: "OAKFOREST", name: "Oak Forest" },
    { id: "TINLEY80TH", name: "Tinley Park - 80th" },
    { id: "TINLEYPARK", name: "Tinley Park" },
    { id: "HICKORYCRK", name: "Hickory Creek" },
    { id: "MOKENA", name: "Mokena" },
    { id: "FRANKFORT", name: "Frankfort" },
    { id: "JOLIET", name: "Joliet" },
  ],
  "ME": [
    { id: "MILLENNIUM", name: "Millennium Station" },
    { id: "VANBUREN", name: "Van Buren Street" },
    { id: "MUSEUM", name: "Museum Campus/11th St." },
    { id: "27TH-UP", name: "27th Street" },
    { id: "MCCORMICK", name: "McCormick Place" },
    { id: "47TH-UP", name: "47th Street" },
    { id: "55-56-57TH", name: "55th-56th-57th Street" },
    { id: "63RD-UP", name: "63rd Street" },
    { id: "95TH-UP", name: "95th Street/Chicago State Univ." },
    { id: "RIVERDALE", name: "Riverdale" },
    { id: "UNIVPARK", name: "University Park" },
  ]
};

export default metraStations;
